### ISSUE TITLE
希望增加火狐扩展

### ISSUE THREAD

**Issue by wentlwr** [krau/Gopeed-Chrome-Extension#10]
大佬的扩展非常好用，只是还有不少人也用火狐浏览器，而且我在gopeed官方issue里也看到有人想要火狐的扩展，我觉得你的扩展比官方的更好用，所以希望大佬能为火狐也开发个扩展

**Comment by krau** [comment]
> 大佬的扩展非常好用，只是还有不少人也用火狐浏览器，而且我在gopeed官方issue里也看到有人想要火狐的扩展，我觉得你的扩展比官方的更好用，所以希望大佬能为火狐也开发个扩展

已经有了哇，看简介里

**Comment by wentlwr** [comment]
> > 大佬的扩展非常好用，只是还有不少人也用火狐浏览器，而且我在gopeed官方issue里也看到有人想要火狐的扩展，我觉得你的扩展比官方的更好用，所以希望大佬能为火狐也开发个扩展
> 
> 已经有了哇，看简介里

没注意，我的问题，谢谢大佬
