### ISSUE TITLE
单击下载链接，无法下载！

### ISSUE THREAD

**Issue by zejunxu** [krau/Gopeed-Chrome-Extension#11]
![image](https://github.com/krau/Gopeed-Chrome-Extension/assets/72739840/6b9d5506-3bb0-4256-8a9f-bac9eb33bf4b)
复制下载链接，添加任务，可以正常下载。
但是直接单击下载链接，无法下载，提示信息见图片。

**Comment by krau** [comment]
看下你的 host 和 token 配置

**Comment by zejunxu** [comment]
![image](https://github.com/krau/Gopeed-Chrome-Extension/assets/72739840/8b4f4ace-7a9e-4500-be40-e6ff3eb47a85)
![image](https://github.com/krau/Gopeed-Chrome-Extension/assets/72739840/8c5a959b-24fd-44ba-9d46-8aa85adb251e)

**Comment by krau** [comment]
> ![image](https://private-user-images.githubusercontent.com/72739840/322005159-8b4f4ace-7a9e-4500-be40-e6ff3eb47a85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzAzODIsIm5iZiI6MTcxMjkzMDA4MiwicGF0aCI6Ii83MjczOTg0MC8zMjIwMDUxNTktOGI0ZjRhY2UtN2E5ZS00NTAwLWJlNDAtZTZmZjNlYjQ3YTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEzNTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZWUzNWI5MWQ5ZWM3OTM5MTQwZWE5YTE4OTRhYjE0M2I0YTMxMzMxYmJiNTA1NGQ1ZTA1MWQzNzM3OGUwZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rSghPopqWPjZOZtsWBt7OOKPSy73Kk2jxqFitJNMpgM) ![image](https://private-user-images.githubusercontent.com/72739840/322005516-8c5a959b-24fd-44ba-9d46-8aa85adb251e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzAzODIsIm5iZiI6MTcxMjkzMDA4MiwicGF0aCI6Ii83MjczOTg0MC8zMjIwMDU1MTYtOGM1YTk1OWItMjRmZC00NGJhLTlkNDYtOGFhODVhZGIyNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEzNTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NmM1ZDc3ZDAyMjAxODFkODRiMmIzNWE4M2YxNmM4MmQzYTRkMjBlNTI0NmZjNzk1NzVlMjk4MmJkYTE2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OUTX-TjYwpE2jSQ71CWgG0q3pRIdz2HUP7lIXE87NU4)

host 前面要加上 http://

**Comment by zejunxu** [comment]
host 前面加了 http:// 后，正常了，Gopeed使用非常方便。谢谢！！！
