### ISSUE TITLE
浏览器插件的问题

### ISSUE THREAD

**Issue by geryson911** [krau/Gopeed-Chrome-Extension#13]
都配置好后可以弹出下载按钮，点击下载后无反应，客户端不会自己开启，手动开启客户端后下载正常，能自动开启客户端么？

**Comment by krau** [comment]
你指的是当 gopeed 不在后台时由插件主动拉起吗

**Comment by Frank1109725833** [comment]
为什么我导入插件，后面edge会自动把这个插件给删除了，导致我需要经常开启开发者模式，然后导入该插件再下载东西

**Comment by Qxy0happy** [comment]
希望大佬支持像IDM插件一样的唤醒能力

**Comment by geryson911** [comment]
> 你指的是当 gopeed 不在后台时由插件主动拉起吗

对，就是这个意思

**Comment by krau** [comment]
此功能需要 Gopeed 自身支持, 目前无法实现
