### ISSUE TITLE
新标签页打开图片唤起gopeed下载图片

### ISSUE THREAD

**Issue by linchuan7** [krau/Gopeed-Chrome-Extension#17]
很好的扩展👍，就是右键新标签页打开图片时会唤起gopeed下载图片，而不是在浏览器看图，不太方便

**Comment by krau** [comment]
试了下我并没有这个问题, 可以提供能够复现的图片网址吗?

**Comment by linchuan7** [comment]
https://www.runningcheese.com/chatgpt

**Comment by krau** [comment]
即使不使用本扩展也会调起浏览器下载而不是在浏览器中预览, 这是图源服务器配置所决定的

![image](https://github.com/user-attachments/assets/b24c1d45-b27e-4b35-9be4-1fc5cb99c3e2)



> https://www.runningcheese.com/chatgpt

**Comment by linchuan7** [comment]
还真是😂，谢回复~
