### ISSUE TITLE
功能请求：增加下载接管开关

### ISSUE THREAD

**Issue by AHCorn** [krau/Gopeed-Chrome-Extension#18]
如题，希望可以增加一个接管开关，选择关闭接管后当前页面的下载不再发送至 Gopeed，以解决部分场景下无法正常下载的问题。

**Comment by krau** [comment]
https://github.com/krau/Gopeed-Chrome-Extension/commit/32f0a5566366254e23c5a78d47622c279025d656

**Comment by AHCorn** [comment]
一小时最速传说

**Comment by AHCorn** [comment]
thanks for your work =￣ω￣=
