### ISSUE TITLE
下载torrent种子文件时提示unsupported protocol

### ISSUE THREAD

**Issue by kyleli666** [krau/Gopeed-Chrome-Extension#19]
在https://bangumi.moe/ 下载torrent种子文件时，能自动拦截到，但会收到unsupported protocol的提示而无法发起下载。

![image](https://github.com/user-attachments/assets/065e948c-1e31-46b4-9477-07186fb2387c)

别的网站没有问题，比如nyaa，不知是不是这个站点的下载链接有什么特殊之处？

**Comment by krau** [comment]
该站点的种子文件是以 blob application/octet-stream 传输个浏览器的, 无法获得下载直链

**Comment by krau** [comment]
https://github.com/krau/Gopeed-Chrome-Extension/commit/f5d96f4
