### ISSUE TITLE
需要填写的host和token应该填写什么内容

### ISSUE THREAD

**Issue by codersun123** [krau/Gopeed-Chrome-Extension#2]
需要填写的host和token应该填写什么内容

**Comment by krau** [comment]
> 需要填写的host和token应该填写什么内容

https://docs.gopeed.com/zh/dev-api.html

**Comment by krau** [comment]
> 然后呢？扩展设置了。。。。然后浏览器的磁力连接也不能自动引入？难道是我浏览器是edge的关系？嘎嘎。。

磁力链接无法自动引入, 因为浏览器本身不支持磁力的下载, 拦截不到

**Comment by TYTZero** [comment]
为什么我的用不了，2和3版本都试过，edge和chrome也试过，是按照你的方法配置的，也看了讨论区确定我这样配置是没有问题的
