### ISSUE TITLE
0.4.1版本导不进来

### ISSUE THREAD

**Issue by wentlwr** [krau/Gopeed-Chrome-Extension#26]
![image](https://github.com/user-attachments/assets/970cb184-784a-4af7-9c2e-a305b5d5cde9)
解压后浏览器导入，如图，好几个浏览器都这样

**Comment by krau** [comment]
ci 有误, 选择 Gopeed-Chrome-Extension/build 文件夹可以正常加载.

下个小版本修复此问题.
