### ISSUE TITLE
这个扩展和gopeed自带的那个扩展是什么区别？

### ISSUE THREAD

**Issue by majw88** [krau/Gopeed-Chrome-Extension#28]
gopeed设置里点浏览器扩展，会打开谷歌商店，那个扩展安装了之后通信上之后就能调用gopeed下载了，所以这个扩展和那个的区别是什么？给我搞蒙了

**Comment by krau** [comment]
谷歌商店上架的为 Gopeed 官方扩展, 本项目是我个人起初由于找不到官方扩展才自行开发的. 你可以自行选择使用.
