### ISSUE TITLE
请问这个插件的使用方法

### ISSUE THREAD

**Issue by hhkbp2** [krau/Gopeed-Chrome-Extension#3]
请问这个插件的功能，使用方法有哪些？有相关的手册吗

**Comment by krau** [comment]
> 请问这个插件的功能，使用方法有哪些？有相关的手册吗

很简单的功能, 没有手册.
安装并设置 host 和 token 后, 自动由 gopeed 执行浏览器中的下载事件

**Comment by hhkbp2** [comment]
好的，谢谢！
