### ISSUE TITLE
提示创建task失败

### ISSUE THREAD

**Issue by 1176749880** [krau/Gopeed-Chrome-Extension#30]
![image](https://github.com/user-attachments/assets/7d2ed98f-002a-45e1-b863-f4d0c2044f8a)

**Comment by AHCorn** [comment]
该报错一般为插件未能与 Gopeed 程序正常通信所致。

### 须知：

1. 本插件依赖于运行在后台的 Gopeed 程序，不能独立运行
2. Gopeed 本体需要手动配置端口号及自定义令牌
3. 插件需要手动在 Host 和 Token 位置输入和 Gopeed 本体相同的配置

### 设置流程如下：

首先从 [Gopeed](https://gopeed.com/zh-CN) 官网或项目主页下载 Gopeed 程序，解压后安装

安装完成后打开到如下界面，点击左侧边栏设置按钮

![设置](https://github.com/user-attachments/assets/416297eb-1ae2-48fd-8a8c-49f516702425)

随后点击顶部的高级一栏，找到 API 位置

![API](https://github.com/user-attachments/assets/d56ab2fc-691b-4c60-90c6-57134188aeec)

1. Gopeed - 设置 - 高级 - API - 点击通讯协议 - 输入端口号

![端口](https://github.com/user-attachments/assets/c0f74988-136c-49ed-96f5-27cb10c483da)

2. Gopeed - 设置 - 高级 - API - 点击接口令牌 - 输入 Token （可理解为自定义连接密码，不输入则为空）

![Token](https://github.com/user-attachments/assets/32dd5a52-feb6-444f-92f6-4e6fa1470e77)

3. 重启 Gopeed 程序，点击关闭为退出到后台，请在任务托盘右键，点击退出

![退出](https://github.com/user-attachments/assets/6f31b209-07f5-47e5-a1d7-33a9fa920bca)


4. 浏览器内点击插件 - Host为 http://127.0.0.1:刚刚输入的端口号

5. 浏览器内点击插件 - Token 为刚刚设置的接口令牌

6. 点击保存，确保自动接管已打开

![插件设置](https://github.com/user-attachments/assets/c4012df9-b7aa-4aec-b348-dd3fa2750307)


7. 确保 Gopeed 已运行在后台

![后台运行](https://github.com/user-attachments/assets/61a5b053-a7ea-4660-a7c5-cde6e1d08715)

8. 按 F5 刷新当前页面，再次尝试下载

若还未能正常运行，请提供包括版本号、运行环境，以及插件控制台日志在内的详细信息，感谢理解。
