### ISSUE TITLE
请问是我使用方法不对吗？

### ISSUE THREAD

**Issue by cj000918** [krau/Gopeed-Chrome-Extension#4]
本插件安装完成之后，点击下载任务，还是浏览器自己下载，并未传递到下载器去下载啊
是否还有什么地方要配置哦？

**Comment by krau** [comment]
> 本插件安装完成之后，点击下载任务，还是浏览器自己下载，并未传递到下载器去下载啊 是否还有什么地方要配置哦？

需要参考 #1 正确设置 host 和 token

**Comment by TYTZero** [comment]
你解决了吗 @cj000918

**Comment by krau** [comment]
https://github.com/krau/Gopeed-Chrome-Extension/releases/tag/v0.1.5
