### ISSUE TITLE
配置好扩展后，下载请求无法交给GoPeed

### ISSUE THREAD

**Issue by wentlwr** [krau/Gopeed-Chrome-Extension#5]
安装了github页面的浏览器扩展，在windows客户端和浏览器扩展中配置相同的ip，端口，以及token，重启后下载文件，提示ERROR when create task. Error message :Failed to fetch
![image](https://github.com/krau/Gopeed-Chrome-Extension/assets/81084625/fc0123e9-13d6-45b2-a42f-be186b90ef5c)
![image](https://github.com/krau/Gopeed-Chrome-Extension/assets/81084625/478ca481-1136-4e7d-bb4d-df3e6cffa2b6)
![image](https://github.com/krau/Gopeed-Chrome-Extension/assets/81084625/69dd5f0e-1924-47a1-be13-c2cd09e5335e)

**Comment by krau** [comment]
host 那里前面要加上 http://

**Comment by wentlwr** [comment]
> host 那里前面要加上 http://

好的，已解决，谢谢大佬。提个小建议，下载的时候希望可以加个弹窗或者提示之类的，用户可以知道客户端已经接收到了下载请求。现在是点击下载按钮，客户端就直接开始下载，浏览器没有任何提示，客户端也不弹窗口，如果不去客户端里查看下载任务，无法确定是否开始下载了。官方的扩展下载时会弹窗，希望大佬也能加个弹窗或者提示之类的，谢谢

**Comment by krau** [comment]
> > host 那里前面要加上 http://
> 
> 好的，已解决，谢谢大佬。提个小建议，下载的时候希望可以加个弹窗或者提示之类的，用户可以知道客户端已经接收到了下载请求。现在是点击下载按钮，客户端就直接开始下载，浏览器没有任何提示，客户端也不弹窗口，如果不去客户端里查看下载任务，无法确定是否开始下载了。官方的扩展下载时会弹窗，希望大佬也能加个弹窗或者提示之类的，谢谢

已添加下载成功时的通知
