### ISSUE TITLE
这是为什么哪里不对吗，能给个详细教程吗？谢谢了

### ISSUE THREAD

**Issue by zhaoxuxu165** [krau/Gopeed-Chrome-Extension#6]
未能成功加载扩展程序
文件
~\Downloads\Gopeed-Chrome-Extension-main
错误
清单文件缺失或不可读取
无法加载清单。

**Comment by zhaoxuxu165** [comment]
![微信截图_20240316165221](https://github.com/krau/Gopeed-Chrome-Extension/assets/163637522/251350e0-c77e-465c-8b91-f71c2fe262ff)

**Comment by krau** [comment]
> ![微信截图_20240316165221](https://private-user-images.githubusercontent.com/163637522/313389950-251350e0-c77e-465c-8b91-f71c2fe262ff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1ODAyOTAsIm5iZiI6MTcxMDU3OTk5MCwicGF0aCI6Ii8xNjM2Mzc1MjIvMzEzMzg5OTUwLTI1MTM1MGUwLWM3N2UtNDY1Yy04YjkxLWY3MWMyZmUyNjJmZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwOTA2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzQ2MzUzYWM4ZWM0NjBkZWNjYzlhYWZhODFhZGNmNTg5ODZkNmI4ZTllY2YyZjgyOGMxMmM0ZDEyZTU3MmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tjffhFvKz-yYKeul8tqaGrNjgqkg26D8ch5sFGN9Vw4)

你下载的是源代码，不是扩展。
用下面这个链接下载吧

https://github.com/krau/Gopeed-Chrome-Extension/releases/download/v0.1.2/Gopeed-Chrome-Extension.zip

**Comment by zhaoxuxu165** [comment]
@krau 
![微信截图_20240316172318](https://github.com/krau/Gopeed-Chrome-Extension/assets/163637522/98a62853-dbb6-462c-b3bc-624925c612c5)
怎么使用

**Comment by zhaoxuxu165** [comment]
![微信截图_20240316172619](https://github.com/krau/Gopeed-Chrome-Extension/assets/163637522/070c56ed-1e4e-42d0-9197-ef5630b9f58c)

**Comment by zhaoxuxu165** [comment]
![微信截图_20240316172726](https://github.com/krau/Gopeed-Chrome-Extension/assets/163637522/142a0fd0-c5e7-4c2e-8093-f2d7bd2aa599)

**Comment by zhaoxuxu165** [comment]
@krau

**Comment by krau** [comment]
> ![微信截图_20240316172955](https://github.com/krau/Gopeed-Chrome-Extension/assets/163637522/d0113dfe-7dda-417a-baa7-407bff4e9093)
> 现在出现这个了
> 

看一下你插件里的 host 和 token 的设置，注意 host 要加上 http://

**Comment by zhaoxuxu165** [comment]
![微信截图_20240316173551](https://github.com/krau/Gopeed-Chrome-Extension/assets/163637522/49429814-9c61-4e32-b866-a624ca711b8f)

**Comment by zhaoxuxu165** [comment]
@krau

**Comment by zhaoxuxu165** [comment]
@krau 哥们？
