### ISSUE TITLE
当文件名称为中文时，文件名会乱码

### ISSUE THREAD

**Issue by wentlwr** [krau/Gopeed-Chrome-Extension#7]
当下载的文件中包含中文字符时，文件名称会变成乱码，测试了下官方提供的插件没有这个问题，排除了下载客户端的问题，希望大佬修复下，谢谢

**Comment by wentlwr** [comment]
![image](https://github.com/krau/Gopeed-Chrome-Extension/assets/81084625/f9fa3c42-6b8f-40ed-850e-1c268d7026a4)

**Comment by krau** [comment]
https://github.com/krau/Gopeed-Chrome-Extension/releases/tag/v0.1.3

已修复, 试一下

**Comment by wentlwr** [comment]
> https://github.com/krau/Gopeed-Chrome-Extension/releases/tag/v0.1.3
> 
> 已修复, 试一下

中文字符已正常显示，感谢大佬
