### ISSUE TITLE
正确配置了，下载的时候还是浏览器下载

### ISSUE THREAD

**Issue by TYTZero** [krau/Gopeed-Chrome-Extension#8]
为什么我的用不了，2和3版本都试过，edge和chrome也试过，是按照你的方法配置的，也看了讨论区确定我这样配置是没有问题的
![image](https://github.com/krau/Gopeed-Chrome-Extension/assets/102344046/2b101a33-030b-437f-a64b-87202385978b)

**Comment by krau** [comment]
下载的时候有什么提示么

**Comment by wentlwr** [comment]
下载的时候要确保gopeed软件在后台运行，并且IP端口以及token要和gopeed保持一致，如果gopeed更改IP端口或token，需要重启客户端

**Comment by TYTZero** [comment]
@krau 下载就是正常浏览器下载  没有变成gopeed下载

**Comment by TYTZero** [comment]
@wentlwr 这些都确定一样  试了很多次了

**Comment by TYTZero** [comment]
@wentlwr 我刚刚试了 纯数字令牌就可以了  ，有字母就不行，我现在也可以用了

**Comment by wwwcd2000** [comment]
用10000以上65534以下的端口号试试..

**Comment by krau** [comment]
https://github.com/krau/Gopeed-Chrome-Extension/releases/tag/v0.1.5
