### ISSUE TITLE
插件偶尔运行，有时跳转有时不跳

### ISSUE THREAD

**Issue by Blackmiku39** [krau/Gopeed-Chrome-Extension#9]
![{1F89FB33-4B8C-4524-B40D-29526305FBF7} png](https://github.com/krau/Gopeed-Chrome-Extension/assets/164715784/fb3fd946-4803-4e09-bb0f-61d7a5da05da)
![{237E1494-6073-4E86-BBD5-40C4C2CF2D8B} png](https://github.com/krau/Gopeed-Chrome-Extension/assets/164715784/466be0b7-25a0-4519-8758-a3005e162622)
请问该如何解决呢

**Comment by Blackmiku39** [comment]
重启扩展程序后可以用一段时间后就无效用不了了

**Comment by Blackmiku39** [comment]
@krau 请问可以帮帮我吗

**Comment by krau** [comment]
奇怪，为什么我自己用就没这些问题。有空我再多测试下吧

**Comment by Blackmiku39** [comment]
> 奇怪，为什么我自己用就没这些问题。有空我再多测试下吧

非常感谢

**Comment by krau** [comment]
https://github.com/krau/Gopeed-Chrome-Extension/releases/tag/v0.1.5

**Comment by Blackmiku39** [comment]
> https://github.com/krau/Gopeed-Chrome-Extension/releases/tag/v0.1.5

这个版本可以解决，非常感谢~(030)~
